remote_theme: just-the-docs/just-the-docs
title: CH224A Module FGV
description: USB-C PD Trigger Board based on CH224A with Arduino/STM32/ESP/ATMEL AVR family support

google_site_verification: "3vZp-k8gtMgMJ3nLLDHTgYO2PMQu4Ub9cA9Y4zSsDBk"
